#pragma once

#include "theory/arith/nia/NiaTypes.h"
#include "theory/arith/nia/preprocess/NiaNormalizer.h"
#include "theory/arith/poly/PolynomialKernel.h"
#include <vector>

namespace xolver {

/**
 * GroebnerIdealReasoner: sound UNSAT refutation by polynomial-ideal saturation.
 *
 * From the active EQUALITY set {p_i = 0}, run a degree-/step-bounded
 * Buchberger-style reduction. If the ideal generated by {p_i} contains a NONZERO
 * CONSTANT (1 ∈ ideal), the system has no common root over ℂ, hence none over
 * ℤ ⊆ ℂ ⇒ UNSAT (Nullstellensatz direction).
 *
 * Complementary to GcdDivisibilityReasoner: GCD proves INTEGER infeasibility of
 * a single equation (2y=1 has a ℂ-root but no ℤ-root); Gröbner proves COMPLEX
 * infeasibility of a SYSTEM (xy=1 ∧ x=0 has no ℂ-root). Both sound.
 *
 * Bounded (degree / pair / step caps) — bails to NoChange when the basis grows
 * past the budget. Only equalities participate (inequalities carry slack).
 */
class GroebnerIdealReasoner {
public:
    explicit GroebnerIdealReasoner(PolynomialKernel& kernel);

    NiaReasoningResult run(const std::vector<NormalizedNiaConstraint>& constraints);

private:
    PolynomialKernel& kernel_;
};

} // namespace xolver
